# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 842dbd60c8d331272fc15aff91015fa81e474253afc62b641896e54a3e4cb76f145868793defad303b8c89e6528be3df70f32c3f7069adbe0b6ffc7a984e4740

test:
  secret_key_base: 781e2cd997884dc70f9e7e8a2c2ed69da23aef901d87c2a4421c770bdfe4903214393a17e33cd8f89813fd476de7bfb9d5282cc745c86083cf7e7bb7cefd872c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
